### ISSUE TITLE
Type checker: more detailed type errors needed

### ISSUE THREAD

**Issue by martin-henz** [source-academy/java-slang#53]
Example:

```
class Test {
    public static void main(String[] args) {
	int x = 0;
        x = x * true;
    }
}
```
javac gives:
```
Test.java:6: error: bad operand types for binary operator '*'
        x = x * true;
              ^
  first type:  int
  second type: boolean
1 error
```
Source Academy gives:
```
Error: bad operand
```
A few improvements possible:
* Since Source Academy typechecks, compiles and runs, we should clearly indicate that it's a type error: `Type error:` instead of just `Error:`
* Line number would be great!
* It would be great to indicate the offending binary operator and the operand types.

**Comment by bryanlohxz** [comment]
I think I will first make sure all errors include location, then look at including the offending character/characters in errors since the error message that I am returning already has a pointer to the general location. 

An example here:
<img width="1263" alt="image" src="https://github.com/source-academy/java-slang/assets/110974917/d3abf0d7-2c9e-490a-a0b8-3e8521c9460a">

**Comment by bryanlohxz** [comment]
At the same time, source academy frontend has a `SourceError` type that defaults to printing the start and end of the offending part of the program in some kind of format, I am thinking of supporting `SourceError` as well onto of the above error message.

**Comment by xyliew25** [comment]
> I am thinking of supporting SourceError as well ontop of the above error message.

Just to tap on, ECE attempted to support `SourceError` already, although still missing location info, can check it out [here](https://github.com/source-academy/java-slang/blob/main/src/ec-evaluator/errors.ts). Perhaps it's a good idea in the long run to share these errors among all components of java-slang, e.g., type checker, compiler, JVM, ECE, as I believe these errors are indifferent to the different components and this improves output consistency as well.
